- hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Stop containers
      command: docker compose down
      args:
        chdir: /var/lib/jenkins/workspace/devopsproject
      ignore_errors: true

    - name: Build containers
      command: docker compose build
      args:
        chdir: /var/lib/jenkins/workspace/devopsproject

    - name: Start containers
      command: docker compose up -d
      args:
        chdir: /var/lib/jenkins/workspace/devopsproject